version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules

  ml-stock:
    build:
      context: ./ml-stock
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./ml-stock:/app
    #   - ./ml-stock/app/data/dataset:/app/app/data/dataset